/* Sangre de Luna · La Ciudadela Vive · 2026-09-28
   Capa progresiva: no modifica Supabase ni autenticación. */
(()=>{if(window.__SDL_CIUDAD_VIVE__)return;window.__SDL_CIUDAD_VIVE__=true;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const K='sdl_ciudadela_vive_v1'; const weekKey=(()=>{const d=new Date(),j=new Date(d.getFullYear(),0,1);return d.getFullYear()+'-W'+Math.ceil((((d-j)/86400000)+j.getDay()+1)/7)})();
const defaults={xp:0,found:[],missions:{},visits:0,lastVisit:null};
let state={...defaults};try{state={...defaults,...JSON.parse(localStorage.getItem(K)||'{}')}}catch{}
state.visits=(state.visits||0)+1;const previous=state.lastVisit;state.lastVisit=new Date().toISOString();
const save=()=>localStorage.setItem(K,JSON.stringify(state));
const addXP=(n)=>{state.xp=(state.xp||0)+n;save();renderProgress()};
const level=()=>1+Math.floor((state.xp||0)/100);
const badges=()=>[{n:'Explorador',ok:state.visits>=2},{n:'Ojo de la Luna',ok:(state.found||[]).length>=1},{n:'Cronista',ok:(state.xp||0)>=100},{n:'Guardián',ok:(state.xp||0)>=250}].filter(x=>x.ok);
const latest=()=>{const rows=$$('.erow');if(!rows.length)return null;const r=rows[rows.length-1];return {chapter:$('.ech',r)?.textContent?.trim()||'ÚLTIMO EPISODIO',title:$('.etitle',r)?.textContent?.trim()||'Continúa la historia',button:$('.etitle',r)}};
function css(){const s=document.createElement('style');s.textContent=`
.livebar{position:relative;z-index:4;width:min(900px,100%);margin:16px auto 0;display:grid;grid-template-columns:1.25fr .75fr;gap:10px;text-align:left}.livecard{border:1px solid #35536c;border-radius:18px;padding:15px;background:linear-gradient(135deg,#07131ee8,#0b1925e8);box-shadow:0 16px 45px #0007;backdrop-filter:blur(12px)}.livecard h3{margin:4px 0 6px;font:700 1.18rem Georgia}.livecard p{margin:0;color:#aebfd0;font-size:.88rem}.live-kicker{color:#8ed3ff;font-size:.65rem;font-weight:900;letter-spacing:.16em}.live-status{display:flex;align-items:center;gap:8px}.live-dot{width:8px;height:8px;border-radius:50%;background:#ff6f78;box-shadow:0 0 12px #ff6f78}.live-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.live-actions a,.live-actions button{border:1px solid #3d5d77;border-radius:999px;padding:8px 11px;background:#0b1823;color:#eaf7ff;font-weight:800;font-size:.74rem;cursor:pointer}.livehub{padding:64px 0;background:radial-gradient(circle at 50% 0,#10283b 0,transparent 35%),#050b11;border-block:1px solid #182b3d}.hubgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.hubcard{padding:18px;border:1px solid #294258;border-radius:18px;background:#08121c}.hubcard h3{font:700 1.25rem Georgia;margin:7px 0}.hubcard p{color:#9eb1c2;font-size:.88rem;min-height:54px}.hubcard .meter{height:7px;background:#101e2b;border-radius:99px;overflow:hidden;margin:10px 0}.hubcard .meter i{display:block;height:100%;background:#8ed3ff}.hubcard a,.hubcard button{display:inline-flex;border:1px solid #3c5b74;border-radius:999px;padding:8px 11px;background:#0d1a25;color:#eaf7ff;font-weight:800;cursor:pointer}.secret{position:fixed;right:14px;bottom:14px;z-index:70;width:38px;height:38px;border:1px solid #36536c;border-radius:50%;background:#07111be8;color:#9edcff;opacity:.38;cursor:pointer}.secret:hover{opacity:1}.chronicle-toast{position:fixed;right:18px;bottom:64px;z-index:100;width:min(360px,90vw);padding:15px;border:1px solid #41647e;border-radius:16px;background:#07111bf2;box-shadow:0 20px 70px #000b;transform:translateY(20px);opacity:0;pointer-events:none;transition:.3s}.chronicle-toast.show{transform:none;opacity:1}.chronicle-toast b{display:block;color:#9edcff;margin-bottom:5px}.badge{display:inline-flex;padding:4px 7px;border:1px solid #38556c;border-radius:999px;margin:3px;font-size:.68rem;color:#bfe8ff}@media(max-width:760px){.livebar,.hubgrid{grid-template-columns:1fr}.livebar{padding:0 4%}.hubcard p{min-height:0}}`;document.head.appendChild(s)}
function toast(t,b){let x=$('#chronicleToast');if(!x){x=document.createElement('div');x.id='chronicleToast';x.className='chronicle-toast';document.body.appendChild(x)}x.innerHTML='<b>'+t+'</b><span>'+b+'</span>';x.classList.add('show');setTimeout(()=>x.classList.remove('show'),5200)}
function renderProgress(){const x=$('#liveProgress');if(!x)return;const pct=(state.xp||0)%100;x.innerHTML='<span class="live-kicker">LA MANADA · NIVEL '+level()+'</span><h3>'+state.xp+' PX de experiencia</h3><div class="meter"><i style="width:'+pct+'%"></i></div><p>'+(badges().length?badges().map(b=>'<span class="badge">'+b.n+'</span>').join(''):'Explora el universo para obtener tu primera insignia.')+'</p>'}
const NEWS_KEY='sdl_ciudadela_episodios_vistos_v1';
function episodeSnapshot(){return $$('.erow').map(r=>[($('.ech',r)?.textContent||'').trim(),($('.etitle',r)?.textContent||'').trim()].join(' · ')).filter(Boolean)}
function readEpisodeSnapshot(){try{const raw=localStorage.getItem(NEWS_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function saveEpisodeSnapshot(){try{localStorage.setItem(NEWS_KEY,JSON.stringify(episodeSnapshot()))}catch{}}
function hasNewEpisode(){const now=episodeSnapshot(),before=readEpisodeSnapshot();return Array.isArray(before)&&now.some(item=>!before.includes(item))}
function rememberAfterWelcome(){const splash=$('.splash:not(.hide)'),enter=splash?.querySelector('.enter');if(splash&&enter){enter.addEventListener('click',()=>setTimeout(saveEpisodeSnapshot,850),{once:true})}else saveEpisodeSnapshot()}
function injectHero(){const hi=$('.hero .hi');if(!hi||$('#liveBar'))return;const l=latest(),isNew=hasNewEpisode(),box=document.createElement('div');box.id='liveBar';box.className='livebar';
const card=document.createElement('div');card.className='livecard';
const kicker=document.createElement('span');kicker.className='live-kicker';kicker.textContent=isNew?'NOVEDAD DESDE TU ÚLTIMA VISITA':'CONTINÚA LA HISTORIA';
const title=document.createElement('h3');title.textContent=l?l.chapter+' · '+l.title:'La Ciudadela sigue cambiando';
const copy=document.createElement('p');copy.textContent=isNew?'Hay un episodio nuevo o actualizado. Retoma la historia desde aquí.':'Encuentra el episodio más reciente y sigue el hilo de la historia.';
const actions=document.createElement('div');actions.className='live-actions';
const continueLink=document.createElement('a');continueLink.href='#episodios';continueLink.textContent='CONTINUAR HISTORIA';
const mapLink=document.createElement('a');mapLink.href='/mapa.html';mapLink.textContent='ABRIR MAPA VIVO';
actions.append(continueLink,mapLink);card.append(kicker,title,copy,actions);
const status=document.createElement('div');status.className='livecard';status.innerHTML='<div class="live-status"><i class="live-dot"></i><span class="live-kicker">ESTADO DE LA CIUDADELA</span></div><h3>Vigilancia elevada</h3><p>La Manada mantiene abiertos los accesos conocidos.</p>';
box.append(card,status);hi.appendChild(box);rememberAfterWelcome()}
function injectHub(){const anchor=$('#episodios')||$('.foot');if(!anchor||$('#liveHub'))return;const sec=document.createElement('section');sec.id='liveHub';sec.className='livehub';sec.innerHTML=`<div class="w"><div class="head"><div><span class="ey">LA CIUDADELA VIVE</span><h2>Tu expedición continúa</h2></div><p>Explora, encuentra archivos y completa pequeñas misiones. El progreso se guarda en este dispositivo.</p></div><div class="hubgrid"><article class="hubcard"><span class="live-kicker">MISIÓN SEMANAL</span><h3>Rastrea la señal</h3><p>Visita el Mapa de las Tierras y después regresa a la Ciudadela.</p><button id="missionMap">INICIAR MISIÓN</button></article><article class="hubcard"><span class="live-kicker">EXPEDIENTE SECRETO</span><h3>Archivo 05 · Gavrik</h3><p>Documento clasificado. Encuentra el símbolo lunar oculto para desbloquearlo.</p><button id="dossierBtn">VER ESTADO</button></article><article class="hubcard" id="liveProgress"></article><article class="hubcard"><span class="live-kicker">MAPA VIVO</span><h3>Territorios de la historia</h3><p>Regresa al mapa para revisar zonas, rutas y puntos de interés.</p><a href="/mapa.html">EXPLORAR MAPA</a></article><article class="hubcard"><span class="live-kicker">ANTERIORMENTE...</span><h3>Recupera el hilo</h3><p>Repasa las historias publicadas antes de continuar con el episodio más reciente.</p><a href="#historias">ABRIR CRÓNICAS</a></article><article class="hubcard"><span class="live-kicker">DECISIÓN DE LA MANADA</span><h3>¿Qué investigarías primero?</h3><p id="voteText">Elige una ruta. Esta consulta es interactiva y no modifica el canon.</p><button data-vote="oeste">Territorio Oeste</button> <button data-vote="ciudadela">Ciudadela</button></article></div></div>`;anchor.parentNode.insertBefore(sec,anchor);renderProgress();
$('#missionMap').onclick=()=>{if(!state.missions['start-'+weekKey]){state.missions['start-'+weekKey]=true;addXP(25)};state.missions.map=true;save();toast('Misión iniciada','El Mapa de las Tierras ha sido marcado como tu siguiente destino.');setTimeout(()=>location.href='/mapa.html?mission=live',900)};
$('#dossierBtn').onclick=()=>toast('Expediente 05',state.found.includes('moon')?'DESBLOQUEADO · Gavrik: identidad vinculada al Alfa Desconocido.':'BLOQUEADO · Busca un símbolo lunar discreto en esta página.');
Array.from(sec.querySelectorAll('[data-vote]')).forEach(b=>b.onclick=()=>{const vk='sdl_vote_'+weekKey;if(!localStorage.getItem(vk))addXP(10);localStorage.setItem(vk,b.dataset.vote);$('#voteText').textContent='Tu elección quedó registrada en este dispositivo: '+b.textContent+'.'})}
function easter(){if($('#moonSecret'))return;const b=document.createElement('button');b.id='moonSecret';b.className='secret';b.title='Una marca casi invisible';b.textContent='☾';b.onclick=()=>{if(!state.found.includes('moon')){state.found.push('moon');addXP(50);toast('EXPEDIENTE DESBLOQUEADO','Archivo 05 · Gavrik. La luna recuerda lo que otros intentaron ocultar.')}else toast('Archivo ya descubierto','Tu insignia Ojo de la Luna permanece activa.');save()};document.body.appendChild(b)}
function returnMission(){if(new URLSearchParams(location.search).get('mission')==='live'){const done='done-'+weekKey;if(!state.missions[done]&&state.missions.mapVisited){state.missions[done]=true;state.missions.mapDone=true;addXP(40);toast('MISIÓN COMPLETADA','Regresaste del mapa. +40 PX para La Manada.')}save()}}
function cronista(){if(previous&&state.visits>1)setTimeout(()=>toast('EL CRONISTA','Desde tu última visita, la Ciudadela mantiene nuevas rutas de exploración. Revisa tu misión y el archivo clasificado.'),1800)}
function init(){css();injectHero();injectHub();easter();returnMission();cronista();save()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,700);
})();