(()=>{"use strict";
if(window.__SDL_EXPERIENCIA_V2__)return;window.__SDL_EXPERIENCIA_V2__=true;
const body=document.body,root=document.documentElement,path=location.pathname,KEY="sdl-ux-last-place",FONT="sdl-ux-font-scale";const getItem=k=>{try{return localStorage.getItem(k)}catch{return null}},setItem=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const catalog=[
["Inicio de la Ciudadela","Regresa a la portada y conoce el universo.","/","inicio ciudadela portada"],
["El libro · El origen de la manada","Conoce el primer libro y cómo adquirirlo.","/libro.html","libro amazon leer comprar origen"],
["Personajes","Explora las fichas de los personajes.","/personajes","personajes protagonistas"],
["Historias","Lee relatos y contenido narrativo.","/historias","historias relatos lectura"],
["Episodios","Encuentra temporadas y videos.","/episodios","episodios capítulos temporadas"],
["Música","Escucha los sonidos de Sangre de Luna.","/musica","música canciones audio"],
["Galería","Explora artes e imágenes oficiales.","/galeria","galería arte imágenes"],
["Mapa de las Tierras","Descubre lugares y territorios.","/mapa","mapa tierras territorios"],
["Recorrido por la Ciudadela","Explora el tour interactivo.","/tour","tour recorrido ciudadela 360"],
["Mi viaje · Test y misiones","Encuentra tu lugar y continúa tus misiones.","/viaje","test quiz preguntas viaje misiones insignias"],
["Fan Club · La Manada","Únete, elige facción y participa.","/fanclub","fan club miembros comunidad facciones"],
["Desafíos de la Manada","Ingresa como miembro para consultar retos y logros.","/desafios","desafíos retos insignias logros"]
];
const css='body{font-size:calc(16px * var(--sdl-ux-scale,1))}.sdl-ux-dock{position:fixed;left:14px;bottom:14px;z-index:1200;display:flex;align-items:center;gap:4px;padding:6px;border:1px solid rgba(158,199,226,.28);border-radius:16px;background:rgba(4,12,20,.92);box-shadow:0 8px 30px rgba(0,0,0,.3);backdrop-filter:blur(14px);color:#eef6ff;font:600 13px/1.2 Arial,sans-serif}'+
'.sdl-ux-dock a,.sdl-ux-dock button{min-height:42px;min-width:42px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:8px 11px;border:0;border-radius:11px;background:transparent;color:inherit;font:inherit;text-decoration:none;cursor:pointer}'+
'.sdl-ux-dock a:hover,.sdl-ux-dock button:hover{background:rgba(130,202,255,.17);color:#9cdbff}'+
'.sdl-ux-dock :focus-visible,.sdl-ux-dialog :focus-visible,.sdl-ux-start a:focus-visible{outline:3px solid #9cdbff;outline-offset:2px}'+
'.sdl-ux-dialog{position:fixed;inset:0;z-index:99990;display:none;place-items:center;padding:16px;background:rgba(0,4,9,.78);backdrop-filter:blur(10px);font:16px/1.5 Arial,sans-serif;color:#edf6ff}.sdl-ux-dialog.open{display:grid}'+
'.sdl-ux-box{width:min(690px,100%);max-height:min(82vh,760px);overflow:hidden;display:grid;grid-template-rows:auto auto minmax(0,1fr);border:1px solid #38566d;border-radius:20px;background:linear-gradient(165deg,#0a1722,#050b11);box-shadow:0 28px 90px #000b}'+
'.sdl-ux-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:18px 20px 8px}.sdl-ux-head h2{margin:0;font:700 1.5rem Georgia,serif;color:#f5f8fb}'+
'.sdl-ux-close{width:42px;height:42px;border:1px solid #38566d;border-radius:50%;background:#0c1a27;color:#fff;font-size:1.3rem;cursor:pointer}'+
'.sdl-ux-search{width:calc(100% - 40px);margin:8px 20px 14px;padding:13px 15px;border:1px solid #52718a;border-radius:12px;background:#02070c;color:#fff;font:inherit}'+
'.sdl-ux-results{overflow:auto;padding:0 14px 16px}.sdl-ux-result{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 8px;border-top:1px solid #233847}'+
'.sdl-ux-result-main{flex:1;min-width:0;border:0;background:none;color:#eef6ff;text-align:left;cursor:pointer}.sdl-ux-result-main strong{display:block;color:#a9dbff;font-size:.95rem}.sdl-ux-result-main small{display:block;margin-top:3px;color:#a7b7c5;font-size:.8rem}'+
'.sdl-ux-share{flex:0 0 auto;padding:8px 10px;border:1px solid #36556e;border-radius:999px;background:#0a1722;color:#e8f5ff;cursor:pointer}.sdl-ux-empty{padding:20px;color:#a9bac9;text-align:center}'+
'.sdl-ux-start{position:relative;z-index:5;padding:26px 0 32px;background:linear-gradient(180deg,#08111a,#0a1520);border-block:1px solid #20364a}.sdl-ux-start-inner{width:min(1160px,94%);margin:auto}'+
'.sdl-ux-start h2{margin:0 0 5px;color:#f0f6fb;font:700 clamp(1.45rem,3vw,2.15rem) Georgia,serif}.sdl-ux-start p{margin:0 0 15px;color:#a9bac9}.sdl-ux-start-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}'+
'.sdl-ux-start a{min-height:88px;display:flex;flex-direction:column;justify-content:center;gap:5px;padding:14px;border:1px solid #2a4358;border-radius:14px;background:linear-gradient(140deg,#0c1b29,#08111a);color:#eef6ff;text-decoration:none;transition:border-color .18s,transform .18s}.sdl-ux-start a:hover{border-color:#8ed3ff;transform:translateY(-2px)}'+
'.sdl-ux-start a b{color:#9cdbff;font-size:.96rem}.sdl-ux-start a span{color:#a9bac9;font-size:.8rem}.sdl-ux-resume{margin-top:14px;padding:12px 14px;border:1px solid #37566d;border-radius:12px;background:#07111b}'+
'.sdl-ux-resume a{min-height:0;display:inline-flex;flex-direction:row;padding:0;border:0;background:none;color:#9cdbff;font-weight:700}.sdl-ux-resume a:hover{transform:none;text-decoration:underline}'+
'.sdl-ux-toast{position:fixed;left:50%;bottom:84px;transform:translateX(-50%);z-index:100000;padding:10px 14px;border-radius:999px;background:#e9f5ff;color:#0a1722;font:700 13px Arial,sans-serif;box-shadow:0 8px 25px #0008}'+
'@media(max-width:760px){body{font-size:calc(16px * var(--sdl-ux-scale,1));padding-bottom:calc(74px + env(safe-area-inset-bottom))!important}.sdl-ux-dock{left:8px;right:8px;bottom:calc(8px + env(safe-area-inset-bottom));justify-content:space-around;gap:1px;padding:5px;border-radius:16px}.sdl-ux-dock a,.sdl-ux-dock button{flex:1;min-width:0;min-height:48px;flex-direction:column;gap:2px;padding:4px 2px;font-size:11px}.sdl-ux-start-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.sdl-ux-start a{min-height:78px;padding:12px}.sdl-ux-dialog{padding:8px}.sdl-ux-box{max-height:88vh;border-radius:16px}#cronistaWidget,#sdlgCronista{bottom:calc(74px + env(safe-area-inset-bottom))!important}.playerbar.show{bottom:calc(76px + env(safe-area-inset-bottom))!important}}'+
'@media(max-width:380px){.sdl-ux-dock a,.sdl-ux-dock button{font-size:10px}.sdl-ux-start-grid{gap:7px}}@media(prefers-reduced-motion:reduce){.sdl-ux-start a{transition:none}.sdl-ux-start a:hover{transform:none}}';
const style=document.createElement("style");style.textContent=css;document.head.appendChild(style);

const lunarStyle=document.createElement("style");lunarStyle.textContent=
'.sdl-ux-dock{border-color:rgba(184,205,222,.35);border-radius:999px;background:linear-gradient(135deg,rgba(7,15,24,.97),rgba(11,27,42,.94));box-shadow:0 8px 28px rgba(0,0,0,.42),inset 0 0 0 1px rgba(231,240,247,.035)}'+
'.sdl-ux-dock:before{content:"";position:absolute;inset:3px;border:1px solid rgba(150,190,219,.12);border-radius:inherit;pointer-events:none}'+
'.sdl-ux-dock a,.sdl-ux-dock button{position:relative;border-radius:999px;letter-spacing:.035em}.sdl-ux-dock [data-sdl-open-menu] span:first-child{color:#b9d8ec;font-size:1.35em}'+
'.sdl-lunar-menu{place-items:stretch end;padding:0;background:rgba(1,5,10,.76)}.sdl-menu-panel{width:min(440px,100%);height:100%;max-height:100%;overflow:auto;padding:clamp(22px,5vw,38px);border-left:1px solid #506a7d;background:radial-gradient(ellipse at 10% 0%,rgba(95,140,171,.18),transparent 37%),linear-gradient(160deg,#0a131d,#03070c 70%);box-shadow:-24px 0 80px #0009}.sdl-menu-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;padding-bottom:22px;border-bottom:1px solid rgba(186,211,228,.2)}'+
'.sdl-menu-kicker{color:#9abbd2;font:800 .66rem Arial,sans-serif;letter-spacing:.2em}.sdl-menu-head h2{margin:6px 0 0;color:#f1f6f9;font:700 clamp(1.8rem,4vw,2.3rem) Georgia,serif}.sdl-menu-groups{display:grid;gap:6px;padding:16px 0}.sdl-menu-link,.sdl-menu-group summary{min-height:48px;display:flex;align-items:center;padding:10px 12px;border:1px solid transparent;border-radius:11px;color:#e9f1f6;text-decoration:none;font:700 .98rem/1.35 Arial,sans-serif;cursor:pointer}.sdl-menu-link:hover,.sdl-menu-group summary:hover{border-color:rgba(152,190,215,.28);background:rgba(171,207,230,.07);color:#c4e8ff}.sdl-menu-group{border:1px solid rgba(145,174,196,.17);border-radius:13px;background:rgba(10,23,34,.54);overflow:hidden}.sdl-menu-group summary{list-style:none;justify-content:space-between;color:#c8dfef;letter-spacing:.025em}.sdl-menu-group summary::-webkit-details-marker{display:none}.sdl-menu-group summary:after{content:"＋";color:#91b6d1;font-weight:400}.sdl-menu-group[open] summary:after{content:"−"}.sdl-menu-links{display:grid;padding:0 9px 9px 17px}.sdl-menu-links a{padding:8px 10px;border-left:1px solid rgba(145,174,196,.28);color:#b7c4cf;text-decoration:none;font:500 .91rem Arial,sans-serif}.sdl-menu-links a:hover{color:#fff;border-color:#b8d9ee}.sdl-menu-tools{display:flex;gap:9px;flex-wrap:wrap;padding-top:15px;border-top:1px solid rgba(186,211,228,.2)}'+
'.sdl-menu-tools button{min-height:44px;padding:10px 13px;border:1px solid #405b70;border-radius:999px;background:#0b1a27;color:#d8e9f4;font:700 .8rem Arial,sans-serif;cursor:pointer}.sdl-menu-tools button:hover{border-color:#a3c9e2;background:#102638}.sdl-menu-tools button span{margin-left:5px}'+
'.top nav.sdl-site-nav{align-items:center;gap:clamp(5px,1vw,15px);font-size:.84rem;letter-spacing:.04em}.top nav.sdl-site-nav .sdl-nav-link,.top nav.sdl-site-nav .sdl-nav-toggle{min-height:40px;display:inline-flex;align-items:center;padding:8px 10px;border:1px solid transparent;border-radius:999px;background:transparent;color:#dbe7ee;text-decoration:none;font:800 .78rem Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap;cursor:pointer}.top nav.sdl-site-nav .sdl-nav-link:hover,.top nav.sdl-site-nav .sdl-nav-toggle:hover,.top nav.sdl-site-nav .sdl-nav-group.is-open>.sdl-nav-toggle{border-color:rgba(169,204,226,.34);background:linear-gradient(135deg,rgba(120,163,190,.12),rgba(21,39,54,.55));color:#c6e6fb}.sdl-nav-group{position:relative}.sdl-nav-panel{position:absolute;top:calc(100% + 8px);left:0;min-width:220px;display:none;gap:2px;padding:9px;border:1px solid #405b70;border-radius:14px;background:linear-gradient(150deg,#0d1a26,#03070c);box-shadow:0 20px 44px #0009}.sdl-nav-group.is-open .sdl-nav-panel{display:grid}.sdl-nav-panel a{padding:10px 11px;border-radius:9px;color:#c8d6df;text-decoration:none;font:600 .86rem Arial,sans-serif}.sdl-nav-panel a:hover{background:rgba(157,197,222,.1);color:#e8f5fc}.sdl-nav-search{min-height:40px;padding:8px 12px;border:1px solid rgba(169,204,226,.28);border-radius:999px;background:rgba(9,22,32,.8);color:#dcebf4;font:700 .78rem Arial,sans-serif;cursor:pointer}.sdl-nav-search:hover{border-color:#9fc6df;color:#c6e6fb}'+
'@media(max-width:900px){.top nav.sdl-site-nav{display:none!important}.sdl-nav-search{display:none}.sdl-ux-dock[data-home="true"]{display:flex!important}}@media(min-width:901px){.sdl-ux-dock[data-home="true"]{display:none!important}}'+
'@media(max-width:760px){.sdl-ux-dock{gap:2px;padding:5px}.sdl-ux-dock a,.sdl-ux-dock button{min-height:49px;font-size:11px}.sdl-menu-panel{width:min(430px,100%);padding:20px 18px calc(22px + env(safe-area-inset-bottom))}.sdl-menu-link,.sdl-menu-group summary{min-height:50px}.top nav.sdl-site-nav .sdl-nav-panel{position:static}}'+
'@media(prefers-reduced-motion:reduce){.sdl-ux-dock *,.sdl-menu-panel *,.sdl-site-nav *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}';
document.head.appendChild(lunarStyle);

const dock=document.createElement("nav");dock.className="sdl-ux-dock";dock.setAttribute("aria-label","Accesos rápidos");
dock.innerHTML='<button type="button" data-sdl-open-menu aria-label="Abrir menú lunar"><span aria-hidden="true">☾</span><span>Menú</span></button><button type="button" data-sdl-open-search aria-label="Buscar en Sangre de Luna"><span aria-hidden="true">⌕</span><span>Buscar</span></button><a href="/" aria-label="Volver al inicio"><span aria-hidden="true">⌂</span><span>Inicio</span></a>';dock.dataset.home=String(path==="/"||path==="/index.html");body.appendChild(dock);
const menu=document.createElement("div");menu.className="sdl-ux-dialog sdl-lunar-menu";menu.id="sdlUxMenu";menu.setAttribute("role","dialog");menu.setAttribute("aria-modal","true");menu.setAttribute("aria-labelledby","sdlMenuTitle");
menu.innerHTML='<section class="sdl-menu-panel"><header class="sdl-menu-head"><div><span class="sdl-menu-kicker">SANGRE DE LUNA</span><h2 id="sdlMenuTitle">Explora el universo</h2></div><button class="sdl-ux-close" type="button" data-sdl-close-menu aria-label="Cerrar menú">×</button></header><div class="sdl-menu-groups"></div><footer class="sdl-menu-tools"><button type="button" data-sdl-font> A↕ <span>Tamaño del texto</span></button><button type="button" data-sdl-share>↗ <span>Compartir esta página</span></button></footer></section>';body.appendChild(menu);
const groupRoot=menu.querySelector(".sdl-menu-groups");
const makeMenuLink=(item)=>{const a=document.createElement("a");a.href=item[2];a.className="sdl-menu-link";a.textContent=item[0];a.addEventListener("click",()=>menu.classList.remove("open"));return a};
const makeDetails=(title,items)=>{const d=document.createElement("details");d.className="sdl-menu-group";const sm=document.createElement("summary");sm.textContent=title;d.appendChild(sm);const list=document.createElement("div");list.className="sdl-menu-links";items.forEach(x=>list.appendChild(makeMenuLink(x)));d.appendChild(list);return d};
const homeEntry=catalog[0],bookEntry=catalog[1],universeEntries=catalog.slice(2,9),communityEntries=catalog.slice(9);
groupRoot.appendChild(makeMenuLink(homeEntry));groupRoot.appendChild(makeDetails("UNIVERSO",universeEntries.slice(0,3)));groupRoot.appendChild(makeDetails("MULTIMEDIA",universeEntries.slice(3,5)));groupRoot.appendChild(makeDetails("EXPLORAR",universeEntries.slice(5)));groupRoot.appendChild(makeDetails("COMUNIDAD",communityEntries));groupRoot.appendChild(makeMenuLink(bookEntry));
const gameUrl="https://sangre-de-luna-ecos-ciudadela.vercel.app/";const gameItem=["Jugar · Crónicas de la Ciudadela","Entra al juego de Sangre de Luna.",gameUrl,"juego jugar"];
groupRoot.appendChild(makeMenuLink(gameItem));
const isWelcome=()=>{const splash=document.getElementById("splash");return !!(splash&&!splash.classList.contains("hide"))};
const openMenu=()=>{if(isWelcome())return;menu.classList.add("open");const first=menu.querySelector(".sdl-menu-link");setTimeout(()=>first&&first.focus(),20)};
const closeMenu=()=>menu.classList.remove("open");
dock.querySelector("[data-sdl-open-menu]").addEventListener("click",openMenu);
menu.querySelector("[data-sdl-close-menu]").addEventListener("click",closeMenu);
menu.addEventListener("click",e=>{if(e.target===menu)closeMenu()});
menu.querySelectorAll("a[href]").forEach(a=>a.addEventListener("click",()=>closeMenu()));
if(document.querySelector(".top nav.nav")){
 const nav=document.querySelector(".top nav.nav");
 if(nav){
  nav.classList.add("sdl-site-nav");nav.setAttribute("aria-label","Navegación principal");nav.replaceChildren();
  const addTopLink=(label,href)=>{const a=document.createElement("a");a.className="sdl-nav-link";a.href=href;a.textContent=label;nav.appendChild(a)};
  const closeGroups=()=>nav.querySelectorAll('.sdl-nav-group').forEach(g=>{g.classList.remove('is-open');g.querySelector('button').setAttribute('aria-expanded','false')});
  const addGroup=(label,items)=>{const wrap=document.createElement('div');wrap.className='sdl-nav-group';const b=document.createElement('button');b.type='button';b.className='sdl-nav-toggle';b.setAttribute('aria-expanded','false');b.textContent=label+'  ⌄';const panel=document.createElement('section');panel.className='sdl-nav-panel';panel.id='sdlMega'+label;b.setAttribute('aria-controls',panel.id);const head=document.createElement('header');head.className='sdl-mega-head';const title=document.createElement('h2');title.textContent=label+' · SANGRE DE LUNA';const close=document.createElement('button');close.type='button';close.className='sdl-mega-close';close.textContent='×';close.setAttribute('aria-label','Cerrar menú '+label);close.onclick=()=>{closeGroups();b.focus()};head.append(title,close);const grid=document.createElement('div');grid.className='sdl-mega-grid';const sections=label==='UNIVERSO'?[['Personajes',[items[0]]],['Historias',[items[1]]],['Episodios',[items[2]]]]:label==='MULTIMEDIA'?[['Música original',[items[0]]],['Galería oficial',[items[1]]]]:label==='EXPLORAR'?[['Territorios',[items[0]]],['Recorridos',[items[1]]]]:[['Tu recorrido',items.slice(0,1)],['La Manada',items.slice(1,2)],['Participa',items.slice(2)]];sections.forEach(([heading,entries])=>{const col=document.createElement('div');const h=document.createElement('h3');h.textContent=heading;col.appendChild(h);entries.forEach(x=>{const a=document.createElement('a');a.href=x[2];const strong=document.createElement('strong');strong.textContent=x[0];const small=document.createElement('small');small.textContent=x[1];a.append(strong,small);a.onclick=closeGroups;col.appendChild(a)});grid.appendChild(col)});panel.append(head,grid);b.addEventListener('click',()=>{const open=!wrap.classList.contains('is-open');closeGroups();wrap.classList.toggle('is-open',open);b.setAttribute('aria-expanded',String(open))});wrap.append(b,panel);nav.appendChild(wrap)};
  addTopLink("INICIO",homeEntry[2]);addGroup("UNIVERSO",universeEntries.slice(0,3));addGroup("MULTIMEDIA",universeEntries.slice(3,5));addGroup("EXPLORAR",universeEntries.slice(5));addGroup("COMUNIDAD",communityEntries);addTopLink("JUGAR",gameUrl);
  document.addEventListener("click",e=>{if(!e.target.closest(".sdl-nav-group"))nav.querySelectorAll(".sdl-nav-group").forEach(g=>{g.classList.remove("is-open");g.querySelector("button").setAttribute("aria-expanded","false")})});
  document.addEventListener("keydown",e=>{if(e.key==="Escape"){nav.querySelectorAll(".sdl-nav-group").forEach(g=>{g.classList.remove("is-open");g.querySelector("button").setAttribute("aria-expanded","false")})}});
 }
 const actions=document.querySelector('.head-actions');if(actions){const fan=actions.querySelector('.fanclub-head-btn'),admin=actions.querySelector('.admin-entry');if(fan)fan.textContent='FAN CLUB';if(admin){admin.textContent='INGRESAR';admin.href='/?admin=1'}actions.querySelectorAll('[data-sdl-open-search]').forEach(x=>x.remove());const form=document.createElement('form');form.className='sdl-header-search';form.setAttribute('role','search');form.innerHTML='<input type="search" placeholder="Buscar en Sangre de Luna" aria-label="Buscar en Sangre de Luna"><button type="submit" aria-label="Buscar"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg></button>';form.onsubmit=e=>{e.preventDefault();openSearch();input.value=form.querySelector('input').value;showResults()};actions.appendChild(form)}
 const navStyle=document.createElement('style');navStyle.textContent=`
 .top:has(.sdl-site-nav){display:grid!important;grid-template-columns:auto 1fr;padding:12px 3% 0!important;gap:12px 24px;background:#0b1823!important;overflow:visible!important}.top:has(.sdl-site-nav)>a{grid-column:1;grid-row:1}.top:has(.sdl-site-nav) .head-actions{grid-column:2;grid-row:1;justify-content:flex-end;display:flex;flex-wrap:wrap;gap:12px}.top nav.sdl-site-nav{position:relative;grid-column:1/-1;grid-row:2;display:flex!important;gap:0;margin:0 -3.2%;padding:0 3%;background:#030a11;border-top:1px solid #263f53;min-height:54px}.top nav.sdl-site-nav>.sdl-nav-link,.top nav.sdl-site-nav .sdl-nav-toggle{border-radius:0;min-height:54px;padding:14px 24px;font-size:.85rem;text-transform:uppercase;letter-spacing:.055em}.top nav.sdl-site-nav>.sdl-nav-link:not(.sdl-nav-link),.top nav.sdl-site-nav>a:not(.sdl-nav-link){display:none!important}.sdl-nav-group{position:static}.sdl-nav-group.is-open>.sdl-nav-toggle{background:#152b3d!important;position:relative}.sdl-nav-group.is-open>.sdl-nav-toggle:after{content:'';position:absolute;bottom:-1px;left:calc(50% - 8px);border:8px solid transparent;border-bottom-color:#112334}.sdl-nav-panel{top:100%;left:3%;right:3%;width:auto;min-width:0;padding:24px 30px 30px;border-radius:0 0 16px 16px;background:#112334;box-shadow:0 24px 50px #000b;max-height:70vh;overflow:auto}.sdl-mega-head{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #365065;padding-bottom:14px;margin-bottom:22px}.sdl-mega-head h2{font:700 1.45rem Georgia;margin:0;color:#e7f2fa}.sdl-mega-close{border:0;background:none;color:#e2eef6;font-size:28px;cursor:pointer;width:44px;height:44px}.sdl-mega-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:32px}.sdl-mega-grid h3{color:#9ec8e3;font:700 .72rem Arial;letter-spacing:.13em;text-transform:uppercase;margin:0 0 12px}.sdl-nav-panel a{display:block;padding:12px 0;border-radius:0;border-bottom:1px solid #284155}.sdl-nav-panel a strong{font-size:.95rem;display:block}.sdl-nav-panel a small{font-size:.8rem;display:block;color:#a5bacb;margin-top:5px;line-height:1.5}.sdl-header-search{display:flex;width:clamp(210px,24vw,340px);height:42px;border:1px solid #57758a;background:#f0f5f8;border-radius:4px;overflow:hidden}.sdl-header-search input{min-width:0;flex:1;padding:10px 12px;border:0;background:transparent;color:#122638;font:14px Arial}.sdl-header-search button{width:44px;border:0;border-left:1px solid #a9bbc7;background:#cfdee8;color:#193c54;cursor:pointer}.sdl-header-search svg{width:22px;height:22px;fill:none;stroke:currentColor;stroke-width:1.8}.sdl-site-nav :focus-visible,.sdl-header-search :focus-visible{outline:2px solid #b4dfff;outline-offset:-3px}
 @media(max-width:900px){.top:has(.sdl-site-nav){grid-template-columns:1fr;gap:10px;padding:10px 14px!important}.top:has(.sdl-site-nav) .head-actions{grid-column:1;grid-row:2;justify-content:flex-start;gap:8px}.top nav.sdl-site-nav{display:none!important}.sdl-header-search{width:100%;order:10}.head-actions .game-head-btn{display:none!important}.top:has(.sdl-site-nav)>a{justify-self:start}}`;
 document.head.appendChild(navStyle);

}

const dialog=document.createElement("div");dialog.className="sdl-ux-dialog";dialog.id="sdlUxSearch";dialog.setAttribute("role","dialog");dialog.setAttribute("aria-modal","true");dialog.setAttribute("aria-labelledby","sdlUxTitle");
dialog.innerHTML='<div class="sdl-ux-box"><div class="sdl-ux-head"><h2 id="sdlUxTitle">Buscar en Sangre de Luna</h2><button class="sdl-ux-close" type="button" aria-label="Cerrar búsqueda">×</button></div><input class="sdl-ux-search" type="search" autocomplete="off" placeholder="Personaje, lugar, capítulo, libro…" aria-label="Escribe qué quieres encontrar"><div class="sdl-ux-results" aria-live="polite"></div></div>';body.appendChild(dialog);
const input=dialog.querySelector("input"),results=dialog.querySelector(".sdl-ux-results"),close=dialog.querySelector(".sdl-ux-close");
function slug(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)||"contenido"}
function localItems(){return Array.from(document.querySelectorAll(".person,.story,.etitle,.gallery-card,.track,.territory-copy,.hotspot,[data-challenge-card]")).filter(el=>el.getClientRects().length).map((el,i)=>{const title=(el.innerText||el.getAttribute("aria-label")||"").replace(/\s+/g," ").trim().slice(0,110);if(!title)return null;if(!el.id)el.id="sdl-contenido-"+slug(title)+"-"+i;return{title:title.split(" · ")[0],desc:"Contenido de esta página",href:location.pathname+location.search+"#"+el.id,terms:title.toLowerCase(),target:el}}).filter(Boolean)}
function norm(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function showResults(){const q=norm(input.value.trim()),local=localItems(),all=[...catalog.map(x=>({title:x[0],desc:x[1],href:x[2],terms:x[0]+" "+x[1]+" "+x[3]})),...local];const found=(q?all.filter(x=>norm(x.title+" "+x.desc+" "+x.terms).includes(q)):all.slice(0,catalog.length)).slice(0,22);results.replaceChildren();if(!found.length){const p=document.createElement("p");p.className="sdl-ux-empty";p.textContent="No encontré coincidencias. Prueba con otro nombre, lugar o capítulo.";results.appendChild(p);return}found.forEach(item=>{const row=document.createElement("div");row.className="sdl-ux-result";const main=document.createElement("button");main.type="button";main.className="sdl-ux-result-main";const b=document.createElement("strong");b.textContent=item.title;const sm=document.createElement("small");sm.textContent=item.desc;main.append(b,sm);main.addEventListener("click",()=>{dialog.classList.remove("open");if(item.target){item.target.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"});if(item.target.matches(".person,.story-click,.etitle,.gallery-card,.hotspot"))setTimeout(()=>item.target.click(),120)}else location.href=item.href});const sh=document.createElement("button");sh.type="button";sh.className="sdl-ux-share";sh.textContent="Compartir";sh.addEventListener("click",()=>shareUrl(new URL(item.href,location.origin).href,item.title));row.append(main,sh);results.appendChild(row)})}
function openSearch(){if(isWelcome())return;dialog.classList.add("open");input.value="";showResults();setTimeout(()=>input.focus(),30)}
function toast(s){const t=document.createElement("div");t.className="sdl-ux-toast";t.setAttribute("role","status");t.textContent=s;body.appendChild(t);setTimeout(()=>t.remove(),2300)}
async function shareUrl(url,title){const data={title:title||document.title,text:"Explora "+(title||document.title)+" en Sangre de Luna.",url};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(url);toast("Enlace copiado para compartir.")}else{const x=document.createElement("textarea");x.value=url;body.appendChild(x);x.select();document.execCommand("copy");x.remove();toast("Enlace copiado para compartir.")}}catch(e){if(e.name!=="AbortError")toast("No se pudo compartir. Puedes copiar el enlace desde el navegador.")}}
document.querySelectorAll("[data-sdl-open-search]").forEach(b=>b.addEventListener("click",openSearch));input.addEventListener("input",showResults);close.addEventListener("click",()=>dialog.classList.remove("open"));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.classList.remove("open")});document.addEventListener("keydown",e=>{if(e.key==="Escape"){dialog.classList.remove("open");closeMenu()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch()}});
document.querySelectorAll("[data-sdl-font]").forEach(b=>b.addEventListener("click",()=>{const levels=[1,1.1,1.2],current=Number(getItem(FONT)||1),next=levels[(levels.indexOf(current)+1)%levels.length];setItem(FONT,String(next));root.style.setProperty("--sdl-ux-scale",String(next));toast("Texto al "+Math.round(next*100)+"%.")}));
const savedScale=Number(getItem(FONT)||1);if([1,1.1,1.2].includes(savedScale))root.style.setProperty("--sdl-ux-scale",String(savedScale));menu.querySelector("[data-sdl-share]").addEventListener("click",()=>shareUrl(location.href,document.title));
const last=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}})();
function remember(url,title){try{setItem(KEY,JSON.stringify({url,title}))}catch{}}
if(path!=="/"&&path!=="/index.html")remember(location.pathname+location.search+location.hash,document.title.replace(/\s*\|\s*Sangre de Luna.*/i,""));
document.addEventListener("click",e=>{const a=e.target.closest("a[href]");if(!a)return;try{const u=new URL(a.href,location.href);if(u.origin===location.origin&&u.pathname!=="/"&&u.pathname!=="/index.html")remember(u.pathname+u.search+u.hash,(a.innerText||a.getAttribute("aria-label")||document.title).replace(/\s+/g," ").trim())}catch{}});
if(path==="/"||path==="/index.html"){const hero=document.querySelector("#inicio.hero");if(hero&&!document.querySelector(".sdl-ux-start")){const section=document.createElement("section");section.className="sdl-ux-start";section.setAttribute("aria-labelledby","sdlStartTitle");section.innerHTML='<div class="sdl-ux-start-inner"><h2 id="sdlStartTitle">¿Qué quieres descubrir?</h2><p>Elige cómo comenzar tu recorrido por Sangre de Luna.</p><div class="sdl-ux-start-grid"><a href="/libro.html"><b>Leer el libro</b><span>Conoce el origen de la Manada.</span></a><a href="/mapa"><b>Explorar las Tierras</b><span>Descubre lugares y territorios.</span></a><a href="/viaje"><b>Hacer el test</b><span>Encuentra tu lugar y empieza tus misiones.</span></a><a href="/fanclub"><b>Unirme a la Manada</b><span>Participa en el Fan Club oficial.</span></a></div></div>';hero.after(section)}if(last&&last.url&&last.url!=="/"){const start=document.querySelector(".sdl-ux-start");if(start){const box=document.createElement("div");box.className="sdl-ux-resume";const label=document.createElement("b");label.textContent="¿Quieres continuar? ";const a=document.createElement("a");a.href=last.url;a.textContent="Retomar: "+(last.title||"tu última visita")+" →";box.append(label,a);start.querySelector(".sdl-ux-start-inner").appendChild(box)}}}
})();
