(()=>{"use strict";
if(window.__SDL_EXPERIENCIA_V1__)return;window.__SDL_EXPERIENCIA_V1__=true;
const body=document.body,root=document.documentElement,path=location.pathname,KEY="sdl-ux-last-place",FONT="sdl-ux-font-scale";const getItem=k=>{try{return localStorage.getItem(k)}catch{return null}},setItem=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const catalog=[
["Inicio de la Ciudadela","Regresa a la portada y conoce el universo.","/#inicio","inicio ciudadela portada"],
["El libro · El origen de la manada","Conoce el primer libro y cómo adquirirlo.","/#libro","libro amazon leer comprar origen"],
["Personajes","Explora las fichas de los personajes.","/#personajes","personajes protagonistas"],
["Historias","Lee relatos y contenido narrativo.","/#historias","historias relatos lectura"],
["Episodios","Encuentra temporadas y videos.","/#episodios","episodios capítulos temporadas"],
["Música","Escucha los sonidos de Sangre de Luna.","/#musica","música canciones audio"],
["Galería","Explora artes e imágenes oficiales.","/#galeria","galería arte imágenes"],
["Mapa de las Tierras","Descubre lugares y territorios.","/mapa.html","mapa tierras territorios"],
["Recorrido por la Ciudadela","Explora el tour interactivo.","/tour.html","tour recorrido ciudadela 360"],
["Mi viaje · Test y misiones","Encuentra tu lugar y continúa tus misiones.","/viaje.html","test quiz preguntas viaje misiones insignias"],
["Fan Club · La Manada","Únete, elige facción y participa.","/fanclub.html","fan club miembros comunidad facciones"],
["Desafíos de la Manada","Consulta retos y logros.","/fanclub.html#desafios","desafíos retos insignias logros"]
];
const css='body{font-size:calc(16px * var(--sdl-ux-scale,1))}.sdl-ux-dock{position:fixed;left:14px;bottom:14px;z-index:1200;display:flex;align-items:center;gap:4px;padding:6px;border:1px solid rgba(158,199,226,.28);border-radius:16px;background:rgba(4,12,20,.92);box-shadow:0 8px 30px rgba(0,0,0,.3);backdrop-filter:blur(14px);color:#eef6ff;font:600 13px/1.2 Arial,sans-serif}'+
'.sdl-ux-dock a,.sdl-ux-dock button{min-height:42px;min-width:42px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:8px 11px;border:0;border-radius:11px;background:transparent;color:inherit;font:inherit;text-decoration:none;cursor:pointer}'+
'.sdl-ux-dock a:hover,.sdl-ux-dock button:hover{background:rgba(130,202,255,.17);color:#9cdbff}'+
'.sdl-ux-dock :focus-visible,.sdl-ux-dialog :focus-visible,.sdl-ux-start a:focus-visible{outline:3px solid #9cdbff;outline-offset:2px}'+
'.sdl-ux-dialog{position:fixed;inset:0;z-index:99990;display:none;place-items:center;padding:16px;background:rgba(0,4,9,.78);backdrop-filter:blur(10px);font:16px/1.5 Arial,sans-serif;color:#edf6ff}.sdl-ux-dialog.open{display:grid}'+
'.sdl-ux-box{width:min(690px,100%);max-height:min(82vh,760px);overflow:hidden;display:grid;grid-template-rows:auto auto minmax(0,1fr);border:1px solid #38566d;border-radius:20px;background:linear-gradient(165deg,#0a1722,#050b11);box-shadow:0 28px 90px #000b}'+
'.sdl-ux-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:18px 20px 8px}.sdl-ux-head h2{margin:0;font:700 1.5rem Georgia,serif;color:#f5f8fb}'+
'.sdl-ux-close{width:42px;height:42px;border:1px solid #38566d;border-radius:50%;background:#0c1a27;color:#fff;font-size:1.3rem;cursor:pointer}'+
'.sdl-ux-search{width:calc(100% - 40px);margin:8px 20px 14px;padding:13px 15px;border:1px solid #52718a;border-radius:12px;background:#02070c;color:#fff;font:inherit}'+
'.sdl-ux-results{overflow:auto;padding:0 14px 16px}.sdl-ux-result{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 8px;border-top:1px solid #233847}'+
'.sdl-ux-result-main{flex:1;min-width:0;border:0;background:none;color:#eef6ff;text-align:left;cursor:pointer}.sdl-ux-result-main strong{display:block;color:#a9dbff;font-size:.95rem}.sdl-ux-result-main small{display:block;margin-top:3px;color:#a7b7c5;font-size:.8rem}'+
'.sdl-ux-share{flex:0 0 auto;padding:8px 10px;border:1px solid #36556e;border-radius:999px;background:#0a1722;color:#e8f5ff;cursor:pointer}.sdl-ux-empty{padding:20px;color:#a9bac9;text-align:center}'+
'.sdl-ux-start{position:relative;z-index:5;padding:26px 0 32px;background:linear-gradient(180deg,#08111a,#0a1520);border-block:1px solid #20364a}.sdl-ux-start-inner{width:min(1160px,94%);margin:auto}'+
'.sdl-ux-start h2{margin:0 0 5px;color:#f0f6fb;font:700 clamp(1.45rem,3vw,2.15rem) Georgia,serif}.sdl-ux-start p{margin:0 0 15px;color:#a9bac9}.sdl-ux-start-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}'+
'.sdl-ux-start a{min-height:88px;display:flex;flex-direction:column;justify-content:center;gap:5px;padding:14px;border:1px solid #2a4358;border-radius:14px;background:linear-gradient(140deg,#0c1b29,#08111a);color:#eef6ff;text-decoration:none;transition:border-color .18s,transform .18s}.sdl-ux-start a:hover{border-color:#8ed3ff;transform:translateY(-2px)}'+
'.sdl-ux-start a b{color:#9cdbff;font-size:.96rem}.sdl-ux-start a span{color:#a9bac9;font-size:.8rem}.sdl-ux-resume{margin-top:14px;padding:12px 14px;border:1px solid #37566d;border-radius:12px;background:#07111b}'+
'.sdl-ux-resume a{min-height:0;display:inline-flex;flex-direction:row;padding:0;border:0;background:none;color:#9cdbff;font-weight:700}.sdl-ux-resume a:hover{transform:none;text-decoration:underline}'+
'.sdl-ux-toast{position:fixed;left:50%;bottom:84px;transform:translateX(-50%);z-index:100000;padding:10px 14px;border-radius:999px;background:#e9f5ff;color:#0a1722;font:700 13px Arial,sans-serif;box-shadow:0 8px 25px #0008}'+
'@media(max-width:760px){body{font-size:calc(16px * var(--sdl-ux-scale,1));padding-bottom:calc(74px + env(safe-area-inset-bottom))!important}.sdl-ux-dock{left:8px;right:8px;bottom:calc(8px + env(safe-area-inset-bottom));justify-content:space-around;gap:1px;padding:5px;border-radius:16px}.sdl-ux-dock a,.sdl-ux-dock button{flex:1;min-width:0;min-height:48px;flex-direction:column;gap:2px;padding:4px 2px;font-size:11px}.sdl-ux-start-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.sdl-ux-start a{min-height:78px;padding:12px}.sdl-ux-dialog{padding:8px}.sdl-ux-box{max-height:88vh;border-radius:16px}#cronistaWidget,#sdlgCronista{bottom:calc(74px + env(safe-area-inset-bottom))!important}.playerbar.show{bottom:calc(76px + env(safe-area-inset-bottom))!important}}'+
'@media(max-width:380px){.sdl-ux-dock a,.sdl-ux-dock button{font-size:10px}.sdl-ux-start-grid{gap:7px}}@media(prefers-reduced-motion:reduce){.sdl-ux-start a{transition:none}.sdl-ux-start a:hover{transform:none}}';
const style=document.createElement("style");style.textContent=css;document.head.appendChild(style);
const dock=document.createElement("nav");dock.className="sdl-ux-dock";dock.setAttribute("aria-label","Accesos rápidos");
dock.innerHTML='<a href="/" aria-label="Volver al inicio"><span aria-hidden="true">⌂</span><span>Inicio</span></a><button type="button" data-sdl-open-search aria-label="Buscar en Sangre de Luna"><span aria-hidden="true">⌕</span><span>Buscar</span></button><a href="/viaje.html" aria-label="Ir a Mi viaje, test y misiones"><span aria-hidden="true">◇</span><span>Test / Viaje</span></a><button type="button" data-sdl-font aria-label="Ajustar tamaño del texto"><span aria-hidden="true">A↕</span><span>Texto</span></button><button type="button" data-sdl-share aria-label="Compartir esta página"><span aria-hidden="true">↗</span><span>Compartir</span></button>';body.appendChild(dock);
const dialog=document.createElement("div");dialog.className="sdl-ux-dialog";dialog.id="sdlUxSearch";dialog.setAttribute("role","dialog");dialog.setAttribute("aria-modal","true");dialog.setAttribute("aria-labelledby","sdlUxTitle");
dialog.innerHTML='<div class="sdl-ux-box"><div class="sdl-ux-head"><h2 id="sdlUxTitle">Buscar en Sangre de Luna</h2><button class="sdl-ux-close" type="button" aria-label="Cerrar búsqueda">×</button></div><input class="sdl-ux-search" type="search" autocomplete="off" placeholder="Personaje, lugar, capítulo, libro…" aria-label="Escribe qué quieres encontrar"><div class="sdl-ux-results" aria-live="polite"></div></div>';body.appendChild(dialog);
const input=dialog.querySelector("input"),results=dialog.querySelector(".sdl-ux-results"),close=dialog.querySelector(".sdl-ux-close");
function slug(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)||"contenido"}
function localItems(){return Array.from(document.querySelectorAll(".person,.story,.etitle,.gallery-card,.track,.territory-copy,.hotspot,[data-challenge-card]")).filter(el=>el.getClientRects().length).map((el,i)=>{const title=(el.innerText||el.getAttribute("aria-label")||"").replace(/\s+/g," ").trim().slice(0,110);if(!title)return null;if(!el.id)el.id="sdl-contenido-"+slug(title)+"-"+i;return{title:title.split(" · ")[0],desc:"Contenido de esta página",href:location.pathname+location.search+"#"+el.id,terms:title.toLowerCase(),target:el}}).filter(Boolean)}
function norm(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function showResults(){const q=norm(input.value.trim()),local=localItems(),all=[...catalog.map(x=>({title:x[0],desc:x[1],href:x[2],terms:x[0]+" "+x[1]+" "+x[3]})),...local];const found=(q?all.filter(x=>norm(x.title+" "+x.desc+" "+x.terms).includes(q)):all.slice(0,catalog.length)).slice(0,22);results.replaceChildren();if(!found.length){const p=document.createElement("p");p.className="sdl-ux-empty";p.textContent="No encontré coincidencias. Prueba con otro nombre, lugar o capítulo.";results.appendChild(p);return}found.forEach(item=>{const row=document.createElement("div");row.className="sdl-ux-result";const main=document.createElement("button");main.type="button";main.className="sdl-ux-result-main";const b=document.createElement("strong");b.textContent=item.title;const sm=document.createElement("small");sm.textContent=item.desc;main.append(b,sm);main.addEventListener("click",()=>{dialog.classList.remove("open");if(item.target){item.target.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"});if(item.target.matches(".person,.story-click,.etitle,.gallery-card,.hotspot"))setTimeout(()=>item.target.click(),120)}else location.href=item.href});const sh=document.createElement("button");sh.type="button";sh.className="sdl-ux-share";sh.textContent="Compartir";sh.addEventListener("click",()=>shareUrl(new URL(item.href,location.origin).href,item.title));row.append(main,sh);results.appendChild(row)})}
function openSearch(){dialog.classList.add("open");input.value="";showResults();setTimeout(()=>input.focus(),30)}
function toast(s){const t=document.createElement("div");t.className="sdl-ux-toast";t.setAttribute("role","status");t.textContent=s;body.appendChild(t);setTimeout(()=>t.remove(),2300)}
async function shareUrl(url,title){const data={title:title||document.title,text:"Explora "+(title||document.title)+" en Sangre de Luna.",url};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(url);toast("Enlace copiado para compartir.")}else{const x=document.createElement("textarea");x.value=url;body.appendChild(x);x.select();document.execCommand("copy");x.remove();toast("Enlace copiado para compartir.")}}catch(e){if(e.name!=="AbortError")toast("No se pudo compartir. Puedes copiar el enlace desde el navegador.")}}
dock.querySelector("[data-sdl-open-search]").addEventListener("click",openSearch);input.addEventListener("input",showResults);close.addEventListener("click",()=>dialog.classList.remove("open"));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.classList.remove("open")});document.addEventListener("keydown",e=>{if(e.key==="Escape")dialog.classList.remove("open");if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch()}});
dock.querySelector("[data-sdl-font]").addEventListener("click",()=>{const levels=[1,1.1,1.2],current=Number(getItem(FONT)||1),next=levels[(levels.indexOf(current)+1)%levels.length];setItem(FONT,String(next));root.style.setProperty("--sdl-ux-scale",String(next));toast("Texto al "+Math.round(next*100)+"%.")});
const savedScale=Number(localStorage.getItem(FONT)||1);if([1,1.1,1.2].includes(savedScale))root.style.setProperty("--sdl-ux-scale",String(savedScale));dock.querySelector("[data-sdl-share]").addEventListener("click",()=>shareUrl(location.href,document.title));
const last=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}})();
function remember(url,title){try{setItem(KEY,JSON.stringify({url,title}))}catch{}}
if(path!=="/"&&path!=="/index.html")remember(location.pathname+location.search+location.hash,document.title.replace(/\s*\|\s*Sangre de Luna.*/i,""));
document.addEventListener("click",e=>{const a=e.target.closest("a[href]");if(!a)return;try{const u=new URL(a.href,location.href);if(u.origin===location.origin&&u.pathname!=="/"&&u.pathname!=="/index.html")remember(u.pathname+u.search+u.hash,(a.innerText||a.getAttribute("aria-label")||document.title).replace(/\s+/g," ").trim())}catch{}});
if(path==="/"||path==="/index.html"){const hero=document.querySelector("#inicio.hero");if(hero&&!document.querySelector(".sdl-ux-start")){const section=document.createElement("section");section.className="sdl-ux-start";section.setAttribute("aria-labelledby","sdlStartTitle");section.innerHTML='<div class="sdl-ux-start-inner"><h2 id="sdlStartTitle">¿Qué quieres descubrir?</h2><p>Elige cómo comenzar tu recorrido por Sangre de Luna.</p><div class="sdl-ux-start-grid"><a href="/libro.html"><b>Leer el libro</b><span>Conoce el origen de la Manada.</span></a><a href="/mapa.html"><b>Explorar las Tierras</b><span>Descubre lugares y territorios.</span></a><a href="/viaje.html"><b>Hacer el test</b><span>Encuentra tu lugar y empieza tus misiones.</span></a><a href="/fanclub.html"><b>Unirme a la Manada</b><span>Participa en el Fan Club oficial.</span></a></div></div>';hero.after(section)}if(last&&last.url&&last.url!=="/"){const start=document.querySelector(".sdl-ux-start");if(start){const box=document.createElement("div");box.className="sdl-ux-resume";const label=document.createElement("b");label.textContent="¿Quieres continuar? ";const a=document.createElement("a");a.href=last.url;a.textContent="Retomar: "+(last.title||"tu última visita")+" →";box.append(label,a);start.querySelector(".sdl-ux-start-inner").appendChild(box)}}}
})();