(()=>{
  'use strict';
  const loadEl=document.getElementById('l');
  const RUNTIME_COMMIT='87436f1352f7693a7660a3fe5b222be7ff1509c8';
  const bases=[
    `https://cdn.jsdelivr.net/gh/sangredelunaia-code/Sangre-de-Luna-Web@${RUNTIME_COMMIT}/game-runtime/v2/`,
    `https://raw.githubusercontent.com/sangredelunaia-code/Sangre-de-Luna-Web/${RUNTIME_COMMIT}/game-runtime/v2/`
  ];
  async function getPart(i){
    let last=null;
    for(const base of bases){
      try{
        const r=await fetch(base+`part${i}.txt`,{cache:'no-store',mode:'cors'});
        if(!r.ok)throw new Error(`HTTP ${r.status}`);
        const t=await r.text();
        if(!t)throw new Error('Respuesta vacía');
        return t;
      }catch(e){last=e}
    }
    throw new Error(`No se pudo cargar la parte ${i+1} del juego: ${last?.message||'error de red'}`);
  }
  const A0='https://cdn.jsdelivr.net/gh/sangredelunaia-code/Sangre-de-Luna-Web@main/assets/';
  const stageCss=`
  /* sdl-public-mobile-fix-v1 */
  #stage0{background:linear-gradient(#02050ad9,#02050af5),url('${A0}tour-360-patio.webp') center/cover}
  .s0{height:100dvh;display:grid;grid-template-rows:52px minmax(0,1fr);overflow:hidden}.s0top{display:flex;justify-content:space-between;align-items:center;padding:7px 12px;background:#05090ef2;border-bottom:1px solid #bddbef2c;gap:10px}.s0body{display:grid;grid-template-columns:220px minmax(0,1fr) 250px;gap:8px;padding:8px;min-height:0}.s0p{background:#0b1420e8;border:1px solid #bddbef2c;border-radius:14px;padding:10px;overflow:hidden}.s0lyk img{width:100%;height:165px;object-fit:cover;border-radius:10px}.s0lyk h2{font:600 23px Georgia;color:#ffe9b5;margin:7px 0}.s0say{font-size:11px;line-height:1.45;padding:9px;background:#ffffff08;border-left:3px solid #d7b66f;border-radius:9px}.s0mid{display:grid;grid-template-rows:auto minmax(0,1fr) auto;gap:7px;min-height:0}.s0arena{display:grid;place-items:center;min-height:0}.s0q{width:min(650px,95%)}.s0q h3{font:600 22px Georgia;margin:5px 0}.s0ans{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.s0ans button,.s0end,.s0go{border:1px solid #d7b66f66;background:#132130;color:#eef7ff;border-radius:10px;padding:9px;font-weight:800;cursor:pointer}.s0end,.s0go{background:linear-gradient(#dec48e,#957044);color:#111}.s0end:disabled{opacity:.3}.s0cards{display:flex;gap:12px;justify-content:center;align-items:center}.s0card{position:relative;width:145px;height:225px;border:2px solid #637c8b;border-radius:14px;overflow:hidden;background:#071019;cursor:pointer}.s0card img{width:100%;height:100%;object-fit:cover}.s0card:after{content:'';position:absolute;inset:0;background:linear-gradient(transparent 45%,#02060bef 84%)}.s0c{position:absolute;z-index:2;left:8px;right:8px;bottom:8px}.s0c b{display:block;font:600 16px Georgia}.s0active{border-color:#d7b66f;box-shadow:0 0 0 4px #d7b66f22}.s0lock{opacity:.3}.s0used{opacity:.55}.s0foot{display:flex;justify-content:space-between;align-items:center;gap:8px}.s0res{font-size:10px;display:flex;gap:5px;flex-wrap:wrap}.s0res span{padding:5px 7px;background:#ffffff08;border-radius:8px}.s0now{padding:9px;background:#162431;border:1px solid #d7b66f55;border-radius:10px}.s0now b{font:600 16px Georgia}.s0dots{display:flex;gap:4px}.s0dots i{width:23px;height:6px;background:#ffffff18;border-radius:999px}.s0dots i.on{background:#d7b66f}.s0done{text-align:center}.s0done img{width:90px;height:90px;object-fit:cover;border-radius:18px}.s0done h2{font:600 28px Georgia;margin:8px 0}
  @media(max-width:820px){.s0{grid-template-rows:46px minmax(0,1fr)}.s0top{padding:5px 8px}.s0top .ey{font-size:8px}.s0top b{font-size:11px}.s0dots i{width:17px}.s0body{grid-template-columns:1fr;grid-template-rows:64px minmax(0,1fr);gap:5px;padding:5px}.s0body>.s0p:last-child{display:none}.s0lyk{display:grid;grid-template-columns:52px minmax(0,1fr);grid-template-rows:18px 1fr;gap:2px 8px;padding:5px 7px}.s0lyk img{width:52px;height:52px;grid-row:1/3;border-radius:9px}.s0lyk .ey{font-size:7px}.s0lyk h2{display:none}.s0say{grid-column:2;font-size:9px;line-height:1.25;padding:5px 7px;overflow:hidden}.s0mid{grid-template-rows:minmax(0,1fr) 42px;gap:5px}.s0mid>.s0p:first-child{display:none}.s0arena{padding:6px}.s0q{width:100%}.s0q h3{font-size:17px;line-height:1.15}.s0q p{font-size:10px}.s0ans{grid-template-columns:1fr;gap:5px;margin-top:7px}.s0ans button{padding:7px;font-size:10px}.s0cards{gap:7px}.s0card{width:min(31vw,116px);height:min(45vw,174px)}.s0c{left:6px;right:6px;bottom:5px}.s0c b{font-size:11px}.s0c p,.s0c small{font-size:8px}.s0foot{padding:5px}.s0res{font-size:8px;gap:3px}.s0res span{padding:3px 5px}.s0end{padding:6px 8px;font-size:9px}.s0done img{width:64px;height:64px}.s0done h2{font-size:20px}.s0done p{font-size:10px;margin:5px 0}.s0go{padding:8px;font-size:10px}}
  @media(max-width:420px){.s0top b{font-size:10px}.s0dots i{width:13px}.s0q h3{font-size:15px}.s0card{width:105px;height:158px}.s0say{font-size:8px}.s0res span:nth-child(n+4){display:none}}
  `;
  const stageJs=`
  (()=>{
    const S0A='${A0}';let s0Step=0,s0Res={i:0,l:0,s:0,d:0};const E=id=>document.getElementById(id);
    function say(t){if(E('zs'))E('zs').textContent=t;try{if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t),vs=speechSynthesis.getVoices()||[],es=vs.filter(v=>/^es([-_]|$)/i.test(v.lang||'')),male=/jorge|diego|pablo|carlos|miguel|juan|andres|andrés|raul|raúl|alvaro|álvaro|male|hombre/i,v=es.find(x=>male.test(x.name||''))||es.find(x=>/^es-(MX|US|419)/i.test(x.lang||''))||es[0];if(v){u.voice=v;u.lang=v.lang}else u.lang='es-MX';u.rate=.9;u.pitch=.72;speechSynthesis.speak(u)}catch(e){}}
    function ensure(){if(E('stage0'))return;const e=document.createElement('section');e.id='stage0';e.className='screen';e.innerHTML='<div class="s0"><div class="s0top"><div><div class="ey">ENTRENAMIENTO OBLIGATORIO</div><b>ETAPA CERO · EL PRIMER RASTRO</b></div><div class="s0dots" id="zd"></div></div><div class="s0body"><aside class="s0p s0lyk"><img src="'+S0A+'lykos-guardian-approved.webp" alt="Lykos"><div class="ey">GUARDIÁN · GUÍA</div><h2>Lykos</h2><div class="s0say" id="zs"></div></aside><main class="s0mid"><div class="s0p"><div class="ey">OPERACIÓN DE ENTRENAMIENTO</div><b>Aprende una ronda completa antes de entrar en campaña.</b></div><div class="s0p s0arena" id="za"></div><div class="s0p s0foot"><div class="s0res" id="zr"></div><button class="s0end" id="ze" disabled>TERMINAR RONDA</button></div></main><aside class="s0p"><div class="ey">AHORA HAZ ESTO</div><div class="s0now" id="zn"></div><p style="font-size:10px;color:#9fb0ba;line-height:1.5">1. Responde el interrogante<br>2. Juega a Kai<br>3. Combina Mapa de Rutas<br>4. Termina la ronda</p></aside></div></div>';document.body.appendChild(e);E('ze').onclick=()=>{if(s0Step===4)finish()}}
    function screen(){try{scr('stage0')}catch(e){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));E('stage0').classList.add('on')}}
    function progress(){E('zd').innerHTML=[1,2,3,4].map(n=>'<i class="'+(s0Step>=n?'on':'')+'"></i>').join('');E('zr').innerHTML='<span>🔎 '+s0Res.i+'</span><span>🤝 '+s0Res.l+'</span><span>♟ '+s0Res.s+'</span><span>🛡 '+s0Res.d+'</span>'}
    function now(n,t,x){E('zn').innerHTML='<b>'+n+' · '+t+'</b><p style="font-size:11px;color:#c4d0d7">'+x+'</p>'}
    function start0(){ensure();s0Step=0;s0Res={i:0,l:0,s:0,d:0};screen();progress();now('0','Escucha a Lykos','Pulsa comenzar entrenamiento.');E('ze').disabled=true;E('za').innerHTML='<div class="s0done"><img src="'+S0A+'lykos-guardian-approved.webp"><div class="ey">ETAPA CERO</div><h2>Antes de entrar a la Ciudadela</h2><p>Lykos te enseñará jugando. Sigue únicamente lo que te indique.</p><button class="s0go" id="zb">COMENZAR ENTRENAMIENTO</button></div>';E('zb').onclick=one;say('Bienvenido a la Ciudadela. Soy Lykos. Antes de comenzar tu campaña, aprenderás conmigo una ronda completa.')}
    function one(){s0Step=1;progress();now('1','Responde el interrogante','Elige una decisión. Cada respuesta fortalece recursos diferentes.');E('za').innerHTML='<div class="s0q"><div class="ey">INTERROGANTE DE ENTRENAMIENTO</div><h3>Una señal de la puerta no coincide con el registro. ¿Qué harás primero?</h3><div class="s0ans"><button data-s0a="i">Comparar con el registro<br><small>🔎 +2 Información</small></button><button data-s0a="l">Avisar a la Guardia<br><small>🤝 +2 Lealtad</small></button></div></div>';document.querySelectorAll('[data-s0a]').forEach(b=>b.onclick=()=>{b.dataset.s0a==='i'?s0Res.i+=2:s0Res.l+=2;progress();two()});say('Cada ronda comienza con un interrogante. Elige cómo responder.')}
    function two(){s0Step=2;progress();now('2','Juega a Kai Voss','La carta iluminada es la que debes usar ahora.');E('za').innerHTML='<div class="s0cards"><div class="s0card s0active" id="zk"><img src="'+S0A+'kai.webp"><div class="s0c"><small>PERSONAJE</small><b>Kai Voss</b><p>🔎 +2 · ♟ +1</p></div></div><div class="s0card s0lock"><img src="'+S0A+'mapa-tierras-sangre-de-luna.webp"><div class="s0c"><b>Mapa de Rutas</b></div></div></div>';E('zk').onclick=()=>{s0Res.i+=2;s0Res.s++;progress();three()};say('Ahora juega a Kai Voss. Kai aumenta Información y Estrategia.')}
    function three(){s0Step=3;progress();now('3','Combina una carta de apoyo','Juega Mapa de Rutas para complementar a Kai.');E('za').innerHTML='<div class="s0cards"><div class="s0card s0used"><img src="'+S0A+'kai.webp"><div class="s0c"><b>Kai Voss</b><p>Ya fue jugado</p></div></div><div class="s0card s0active" id="zm"><img src="'+S0A+'mapa-tierras-sangre-de-luna.webp"><div class="s0c"><small>APOYO</small><b>Mapa de Rutas</b><p>🔎 +1 · ♟ +1</p></div></div></div>';E('zm').onclick=()=>{s0Res.i++;s0Res.s++;progress();four()};say('Combina a Kai con Mapa de Rutas para completar mejor tus objetivos.')}
    function four(){s0Step=4;progress();now('4','Termina la ronda','Ya decidiste y jugaste tus cartas. Ahora cierra la ronda.');E('za').innerHTML='<div class="s0q"><div class="ey">RONDA LISTA</div><h3>Has completado la secuencia básica.</h3><p>En las misiones repetirás este ciclo hasta alcanzar los objetivos.</p></div>';E('ze').disabled=false;say('Perfecto. Pulsa Terminar Ronda.')}
    function finish(){s0Step=5;E('ze').disabled=true;try{sv.tut=true;save()}catch(e){}localStorage.setItem('sdl_stage0_v1','done');E('za').innerHTML='<div class="s0done"><img src="'+S0A+'lykos-guardian-approved.webp"><div class="ey">ENTRENAMIENTO COMPLETADO</div><h2>La Ciudadela te espera</h2><p>Ya sabes responder interrogantes, jugar personajes, combinar apoyos y cerrar rondas.</p><button class="s0go" id="zc">ENTRAR A LA MISIÓN 1</button></div>';now('✓','Etapa CERO completada','La Misión 1 está desbloqueada.');E('zc').onclick=goCampaign;say('Entrenamiento completado. La primera misión ha sido desbloqueada.')}
    function goCampaign(){try{if(typeof campaign==='function'){campaign();return}}catch(e){}try{scr('campaign')}catch(e){}}
    window.stageZeroStart=start0;try{training=start0}catch(e){}const nb=E('new');if(nb)nb.onclick=()=>{try{sv={u:1,done:{},st:0,cmd:0,tut:false};save()}catch(e){}localStorage.removeItem('sdl_stage0_v1');start0()};const cb=E('cont');if(cb)cb.onclick=()=>{let done=localStorage.getItem('sdl_stage0_v1')==='done';try{done=done||!!sv.tut}catch(e){}done?goCampaign():start0()};
  })();`;
  const qEvents=`const events=[
    ['Banderas falsas','tour-360-murallas.webp','Un guardia lleva una insignia que no coincide con el registro. ¿Qué comprobarás primero?',[['Examinar el sello y la insignia',{i:2}],['Calmar a los presentes y contener rumores',{l:2}]]],
    ['Ruta alterada','mapa-tierras-sangre-de-luna.webp','Dos señales indican rutas distintas. ¿Cómo determinarás cuál es la auténtica?',[['Comparar el mapa con los registros',{s:2}],['Seguir las huellas recientes',{i:2}]]],
    ['Mensaje interceptado','tour-360-archivo-nine.webp','Un informe clave nunca llegó a su destino. ¿Cuál será tu primera acción?',[['Rastrear el origen del mensaje',{i:2}],['Restablecer el canal seguro',{l:1,s:1}]]],
    ['Niebla del valle','tour-360-torre.webp','La niebla cubre las rutas y varias patrullas pierden visibilidad. ¿Qué priorizarás?',[['Reforzar los puestos de vigilancia',{d:2}],['Coordinar señales desde la torre',{s:2}]]],
    ['Consejo urgente','tour-360-salon-trono.webp','La Corte exige una recomendación inmediata. ¿Qué presentarás primero?',[['Evidencia verificada',{i:1,l:1}],['Un plan táctico de respuesta',{s:2}]]],
    ['Testimonio contradictorio','tour-360-patio.webp','Dos testigos describen el mismo hecho de manera diferente. ¿Cómo aclararás la verdad?',[['Comparar ambos testimonios',{i:2}],['Reunirlos y buscar un punto en común',{l:2}]]],
    ['Baliza apagada','tour-360-murallas.webp','Una baliza deja de responder justo antes del cambio de guardia. ¿Qué revisarás?',[['La secuencia de activación',{s:2}],['Las marcas alrededor del mecanismo',{i:2}]]],
    ['Puerta sin registro','tour-360-puertas.webp','La puerta norte fue abierta, pero no existe registro oficial. ¿Qué harás?',[['Revisar quién tenía autorización',{i:2}],['Asegurar primero el acceso',{d:2}]]],
    ['Rumor en el patio','tour-360-patio.webp','Un rumor acusa a un aliado sin pruebas. ¿Cómo evitarás que la tensión crezca?',[['Pedir pruebas antes de aceptar la acusación',{i:1,l:1}],['Emitir una versión oficial y calmada',{l:2}]]],
    ['Suministros desviados','tour-360-puertas.webp','Un cargamento llegó a una zona distinta de la indicada. ¿Cuál es tu prioridad?',[['Verificar la ruta escrita en los registros',{i:2}],['Proteger el cargamento mientras investigas',{d:2}]]],
    ['Puente del Este','tour-vampiro-puente.webp','Una señal del puente del Este no coincide con el protocolo acordado. ¿Cómo procederás?',[['Consultar el acuerdo con los aliados',{l:1,s:1}],['Comparar la señal con el patrón original',{i:2}]]],
    ['Archivo incompleto','tour-360-archivo-nine.webp','Falta una página en un expediente reciente. ¿Qué pista buscarás primero?',[['Quién consultó el archivo por última vez',{i:2}],['Qué decisión dependía de esa página',{s:2}]]]
  ].map(x=>({n:x[0],img:x[1],t:x[2],ch:x[3]}));`;
  async function boot(){
    if(loadEl)loadEl.innerHTML='<div><div style="font-size:44px">🌙</div><b>Preparando Crónicas de la Ciudadela…</b><div style="margin-top:8px;color:#9fb0ba;font-size:12px">Cargando el tablero de juego</div></div>';
    const parts=await Promise.all([0,1,2,3,4].map(getPart));let html=parts.join('');
    if(!html.includes('Crónicas de la Ciudadela')||!html.includes('Lykos')||!html.includes('wolf-entry.mp3'))throw new Error('La descarga del juego quedó incompleta.');
    const a=html.indexOf('const events=['),b=html.indexOf('const names=',a);if(a<0||b<=a)throw new Error('No se encontró el bloque de interrogantes.');html=html.slice(0,a)+qEvents+'\n'+html.slice(b);
    const reps=[['<small>EVENTO</small>','<small>INTERROGANTE</small>'],['¿Cómo responderás al evento?','¿Cuál es tu respuesta?'],['responde al evento','responde al interrogante'],['Responde al evento','Responde al interrogante'],['Nueva ronda. Primero responde al evento.','Nueva ronda. Primero responde al interrogante.'],['Cada ronda empieza con un evento.','Cada ronda empieza con un interrogante.'],['1. Responde al evento.','1. Responde al interrogante.'],["u.lang='es-ES';u.rate=.95;u.pitch=.86","u.lang='es-MX';u.rate=.90;u.pitch=.72"],['width=device-width,initial-scale=1','width=device-width,initial-scale=1,viewport-fit=cover']];for(const [x,y] of reps)html=html.split(x).join(y);
    html=html.replace('</head>','<style id="sdl-stage-zero-self-contained">'+stageCss+'</style></head>');
    html=html.replace('</body>','<script id="sdl-stage-zero-self-contained-js">'+stageJs+'<\/script></body>');
    document.open();document.write(html);document.close();
  }
  boot().catch(e=>{console.error(e);if(loadEl)loadEl.innerHTML='<div style="max-width:520px;padding:24px;text-align:center"><div style="font-size:46px">🌙</div><h2 style="margin:10px 0">No pudimos cargar el juego</h2><p style="color:#b9c5cd;line-height:1.5">'+String(e.message||e)+'</p><button onclick="location.reload()" style="margin-top:12px;border:1px solid #d7b66f66;background:linear-gradient(#dec48e,#957044);color:#111;border-radius:12px;padding:11px 18px;font-weight:900">REINTENTAR</button></div>'});
})();