plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sangredeluna.cronicas'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sangredeluna.cronicas'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
