const SB='https://huvramoqtrorcoywipvm.supabase.co';
const SITE='https://sangre-de-luna-public.vercel.app';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
module.exports=async function handler(req,res){
 try{
  const token=String(req.query.token||'').trim();
  if(!/^[0-9a-f-]{36}$/i.test(token)){res.statusCode=404;res.setHeader('Content-Type','text/plain; charset=utf-8');return res.end('Logro no disponible');}
  const cfg=await fetch(`${SB}/functions/v1/site-config`,{cache:'no-store'}).then(r=>r.json());
  const r=await fetch(`${SB}/rest/v1/rpc/fanclub_public_achievement_share`,{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.key,'Authorization':`Bearer ${cfg.key}`},body:JSON.stringify({p_share_token:token})});
  if(!r.ok)throw new Error('Share lookup failed');const d=await r.json();
  if(!d){res.statusCode=404;res.setHeader('Content-Type','text/plain; charset=utf-8');return res.end('Logro no disponible');}
  const title=`${d.badge_name} · Sangre de Luna`,desc=`${d.alias} ha desbloqueado una insignia ${String(d.rarity||'destacada').replaceAll('_',' ')} en La Manada.`,url=`${SITE}/logro/${token}`;
  res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate');res.setHeader('X-Robots-Tag','noindex, follow');
  return res.end(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${esc(url)}"><meta property="og:type" content="website"><meta property="og:site_name" content="Sangre de Luna"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(url)}"><meta property="og:image" content="${esc(d.image_url)}"><meta property="og:image:width" content="1080"><meta property="og:image:height" content="1080"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="twitter:image" content="${esc(d.image_url)}"><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% 0,#17344d,#02060a 52%);color:#eef8ff;font-family:Arial,sans-serif}.wrap{width:min(620px,94vw);text-align:center}.logo{width:180px;max-height:90px;object-fit:contain;margin-bottom:18px}.card{border:1px solid #3d5d77;border-radius:24px;background:#06111bea;padding:18px;box-shadow:0 30px 90px #000a}.card img{width:100%;border-radius:18px;display:block}.tag{display:inline-block;margin-top:18px;padding:6px 10px;border:1px solid #527895;border-radius:999px;color:#99dbff;font-size:12px;font-weight:800;text-transform:uppercase}.card h1{font:700 2rem Georgia,serif;margin:12px 0 7px}.card p{color:#a9bdcc;line-height:1.55}.cta{display:inline-block;margin-top:10px;padding:12px 18px;border-radius:999px;background:#dff3ff;color:#07101a;text-decoration:none;font-weight:900}</style></head><body><main class="wrap"><img class="logo" src="${SITE}/assets/logo-oficial.png" alt="Sangre de Luna"><section class="card"><img src="${esc(d.image_url)}" alt="${esc(d.badge_name)}"><span class="tag">${esc(String(d.rarity||'').replaceAll('_',' '))}</span><h1>${esc(d.badge_name)}</h1><p>${esc(d.alias)} · ${esc(d.level)} · ${Number(d.points)||0} puntos</p><a class="cta" href="${SITE}/fanclub">CONOCER LA MANADA</a></section></main></body></html>`);
 }catch(e){console.error(e);res.statusCode=500;res.setHeader('Content-Type','text/plain; charset=utf-8');return res.end('Sangre de Luna · Logro temporalmente no disponible');}
};